### ISSUE TITLE
Community Chart Suggestion: Zigbee2MQTT

### ISSUE THREAD

**Issue by DjordyKoert** [truenas/apps#856] opened 2024-11-08 15:09 UTC
Github: https://github.com/Koenkk/zigbee2mqtt
Documentation: https://www.zigbee2mqtt.io/guide/installation/02_docker.html
Docker image: https://hub.docker.com/r/koenkk/zigbee2mqtt/ (`koenkk/zigbee2mqtt`)

**Comment by stavros-k** [comment] 2024-11-08 15:09
Duplicate of #532

**Comment by DjordyKoert** [comment] 2024-11-08 15:10
Whoops just saw it aswell, my bad!

**Closed by stavros-k** 2024-11-08 15:09 UTC
