### ISSUE TITLE
Community Chart Suggestion: Traefik

### ISSUE THREAD

**Issue by pierrickrouxel** [truenas/apps#409] opened 2024-09-12 20:08 UTC
Traefik is a great alternative to nginx-proxy-manager. 
I need it to secure services behind an OIDC authorization server.

Docker documentation: [https://doc.traefik.io/traefik/getting-started/quick-start/]()

To be usable, the `label` configuration need to be added to all apps.

See here: [https://doc.traefik.io/traefik/getting-started/quick-start/#traefik-detects-new-services-and-creates-the-route-for-you]()

**Comment by stavros-k** [comment] 2024-09-12 20:12
Duplicate of #148

**Closed by stavros-k** 2024-09-12 20:12 UTC

**Comment by pierrickrouxel** [comment] 2024-09-12 20:17
Sorry 🫣

**Comment by stavros-k** [comment] 2024-09-12 20:17
No worries!
